addSbtPlugin("io.spray"              % "sbt-revolver"             % "0.9.1")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"               % "7.4.0")
addSbtPlugin("org.portable-scala"    % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("org.scala-js"          % "sbt-scalajs"              % "1.10.1")
addSbtPlugin("io.github.davidmweber" % "flyway-sbt"               % "7.4.0")
addSbtPlugin("com.github.sbt"        % "sbt-native-packager"      % "1.9.9")
addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"             % "0.10.1")
